name: Run Tests and Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'

      - name: Install dependencies with local SynthPred
        run: |
          julia --project=. -e '
            using Pkg;
            Pkg.develop(path=".");
            Pkg.instantiate()
          '

      - name: Run tests with coverage
        run: |
          julia --project=. -e '
            using Pkg;
            Pkg.test(coverage=true)
          '

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
          flags: unittests
          name: julia-codecov
          fail_ci_if_error: false
